from enum import Enum


class EventType(str, Enum):
    # Run lifecycle
    RUN_CREATED = "RUN_CREATED"
    CONFIG_SNAPSHOT_SAVED = "CONFIG_SNAPSHOT_SAVED"
    BUDGETS_INITIALIZED = "BUDGETS_INITIALIZED"

    # Inputs
    COMPANY_INTAKE_SAVED = "COMPANY_INTAKE_SAVED"
    ASSUMPTIONS_DRAFT_CREATED = "ASSUMPTIONS_DRAFT_CREATED"
    ASSUMPTIONS_CONFIRMED = "ASSUMPTIONS_CONFIRMED"

    # Planning
    QUERY_PLAN_CREATED = "QUERY_PLAN_CREATED"

    # RAG (Sprint 2)
    RAG_QUERY_EXECUTED = "RAG_QUERY_EXECUTED"
    RAG_RESULTS_FILTERED = "RAG_RESULTS_FILTERED"

    # Grounding (Sprint 3)
    GROUNDING_CALL_REQUESTED = "GROUNDING_CALL_REQUESTED"
    GROUNDING_CALL_COMPLETED = "GROUNDING_CALL_COMPLETED"
    GROUNDING_QUERIES_COUNTED = "GROUNDING_QUERIES_COUNTED"
    EXTERNAL_BUDGET_EXHAUSTED = "EXTERNAL_BUDGET_EXHAUSTED"

    # Reasoning (Sprint 4)
    REASONING_LOOP_STARTED = "REASONING_LOOP_STARTED"
    REASONING_LOOP_COMPLETED = "REASONING_LOOP_COMPLETED"
    MID_GAP_DETECTED = "MID_GAP_DETECTED"
    USER_QUESTION_ASKED = "USER_QUESTION_ASKED"
    USER_ANSWER_RECEIVED = "USER_ANSWER_RECEIVED"
    ESCALATION_TRIGGERED = "ESCALATION_TRIGGERED"
    CONTRADICTION_DETECTED = "CONTRADICTION_DETECTED"
    CONFIDENCE_STAGNATION = "CONFIDENCE_STAGNATION"
    WORKING_MEMORY_UPDATED = "WORKING_MEMORY_UPDATED"

    # Synthesis (Sprint 5)
    OPPORTUNITIES_COMPUTED = "OPPORTUNITIES_COMPUTED"
    ROI_MODEL_COMPUTED = "ROI_MODEL_COMPUTED"
    CONFIDENCE_COMPUTED = "CONFIDENCE_COMPUTED"
    REPORT_RENDERED = "REPORT_RENDERED"

    # Terminal
    RUN_PUBLISHED = "RUN_PUBLISHED"
    STAGE_FAILED = "STAGE_FAILED"
    BUDGET_VIOLATION_BLOCKED = "BUDGET_VIOLATION_BLOCKED"

    # Refinement
    REPORT_REFINED = "REPORT_REFINED"
    ASSUMPTIONS_CORRECTED = "ASSUMPTIONS_CORRECTED"
    OPPORTUNITIES_REMOVED = "OPPORTUNITIES_REMOVED"

    # Memory
    EVIDENCE_PROMOTED = "EVIDENCE_PROMOTED"
    EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
    EVIDENCE_CONTRADICTION = "EVIDENCE_CONTRADICTION"

    # Multi-agent orchestration
    AGENT_SPAWNED = "AGENT_SPAWNED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    HYPOTHESIS_FORMED = "HYPOTHESIS_FORMED"
    HYPOTHESIS_TESTED = "HYPOTHESIS_TESTED"
    HYPOTHESIS_VALIDATED = "HYPOTHESIS_VALIDATED"
    HYPOTHESIS_REJECTED = "HYPOTHESIS_REJECTED"
    USER_INTERACTION_SURFACED = "USER_INTERACTION_SURFACED"
    USER_INTERACTION_RESOLVED = "USER_INTERACTION_RESOLVED"
    SPAWN_REQUESTED = "SPAWN_REQUESTED"
    PHASE_BACKTRACK = "PHASE_BACKTRACK"
    REPORT_STRUCTURE_DECIDED = "REPORT_STRUCTURE_DECIDED"
